# Generated by Django 4.0.4 on 2022-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_auto_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
