# Generated by Django 4.0.4 on 2022-05-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_auto_anio_auto_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
